<Window x:Class="Propotype_Manage.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:ui="http://schemas.trimble.com/fusion"
        xmlns:local="clr-namespace:Propotype_Manage" 
             xmlns:controls ="clr-namespace:Tekla.Structures.Ui.WpfKit.Controls;assembly=Tekla.Structures.Ui.WpfKit"   
        Title="BIM Prototype Manage 0.1"
        Width="1000" Height="600"
        WindowStartupLocation="CenterScreen"
        Icon="ts-ext.ico" Topmost="True">
    <DockPanel>
        <StatusBar DockPanel.Dock="Bottom">
            <TextBlock Text="Not connected" Visibility="{Binding IsConnected, Mode=OneWay, Converter={ui:ConvertBooleanToInverseVisibility}}" />
            <TextBlock Visibility="{Binding IsConnected, Mode=OneWay, Converter={ui:ConvertBooleanToVisibility}}">
        <Run Text="Connected to " />
        <Run Text="{Binding ModelName, Mode=OneWay}" />
            </TextBlock>
        </StatusBar>
        <ui:PublishedView DockPanel.Dock="Right" Margin="2" ViewName="Example.Prototype.Prototype" />
        <StackPanel  Margin="5" DockPanel.Dock="Left" VerticalAlignment="Top">
            <StackPanel Orientation="Horizontal">
                <Button   Command="{ui:CommandHandler AddAssemblys}" Background="LightGray" Height="30" Cursor="Hand">
                    <StackPanel Orientation="Horizontal">
                        <controls:IconView Width="16" Height="16" VerticalAlignment="Center" Icon="{DynamicResource Geometry.Extensions}"/>
                    </StackPanel>
                    <Button.ToolTip>
                        <ToolTip Content="Получить из модели."/>
                    </Button.ToolTip>
                </Button>
                <Button Margin="2"  Background="LightGray" Height="30" Cursor="Hand"  Command="{ui:CommandHandler InsertPartXML}">
                    <StackPanel Orientation="Horizontal">
                        <Image Width="16" Height="16" Margin="0" Source="Images\innovation.png" />
                    </StackPanel>
                    <Button.ToolTip>
                        <ToolTip Content="Вставить выбранный прототип в Модель"/>
                    </Button.ToolTip>
                </Button>
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <ListBox Margin ="5"   MinWidth="42" MinHeight="23"
                         ItemsSource="{Binding InPrefixDirectory.ListSources,Mode=OneWay,UpdateSourceTrigger=PropertyChanged}" 
                         SelectedItem="{Binding InPrefixDirectory.Source,Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}">
                    <ListBox.ItemsPanel>
                        <ItemsPanelTemplate>
                            <WrapPanel Orientation="Horizontal" />
                        </ItemsPanelTemplate>
                    </ListBox.ItemsPanel>
                </ListBox>
            </StackPanel>
            <StackPanel>
                <ui:PublishedView Margin="2" ViewName="Example.Conductor.Conductor" />
            </StackPanel>
        </StackPanel>
    </DockPanel>
</Window>
