<Window x:Class="Propotype_Manage.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:ui="http://schemas.trimble.com/fusion"
        xmlns:local="clr-namespace:Propotype_Manage" 
             xmlns:controls ="clr-namespace:Tekla.Structures.Ui.WpfKit.Controls;assembly=Tekla.Structures.Ui.WpfKit"   
        Title="BIM Prototype Manage 0.1"
        Width="600" Height="440"
        WindowStartupLocation="CenterScreen"
        Icon="ts-ext.ico" Topmost="True">
    <DockPanel>
        <StatusBar DockPanel.Dock="Bottom">
            <TextBlock Text="Not connected" Visibility="{Binding IsConnected, Mode=OneWay, Converter={ui:ConvertBooleanToInverseVisibility}}" />
            <TextBlock Visibility="{Binding IsConnected, Mode=OneWay, Converter={ui:ConvertBooleanToVisibility}}">
        <Run Text="Connected to " />
        <Run Text="{Binding ModelName, Mode=OneWay}" />
            </TextBlock>
        </StatusBar>        
        <StackPanel  Margin="5" DockPanel.Dock="Top" VerticalAlignment="Top">

            <StackPanel Orientation="Horizontal">

                <Button Margin="2" Height="30" Command="{ui:CommandHandler ModifySelectedPart}">Назначить атрибуты</Button>
                <Button Margin="2" Height="30" Command="{ui:CommandHandler GetSelectedPartAttributes}">Считать атирбуты</Button>
                <Button Margin="2" Height="30"  Command="{ui:CommandHandler InsertPartXML}" Cursor="Hand">InsertPart</Button>
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <Label Content="Префикс сборки"/>
                <TextBox Margin="2" Width="80" Text="{Binding Path=PrefixAssembly, Mode=TwoWay}"/>
                <Label Content="№"/>
                <TextBox Margin="2" Width="40" Text="{Binding Path=NumberAssembly, Mode=TwoWay}"/>
                <Label Content="Главная"/>
                <CheckBox x:Name="mainAssembly" IsChecked="{Binding IsMainAssembly, Mode=TwoWay}"/>
                <Label Content="Копия"/>
                <CheckBox x:Name="copyAssembly" IsChecked="{Binding IsCopyAssembly, Mode=TwoWay}"/>
            </StackPanel>
        </StackPanel>
        <StackPanel DockPanel.Dock="Top">
            <ui:PublishedView Margin="2" ViewName="Example.Conductor.Conductor" />
        </StackPanel>
    </DockPanel>
</Window>
